---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter
        args:
          - --path.rootfs=/host
          - --no-collector.arp
          - --no-collector.bcache
          - --no-collector.bonding
          - --no-collector.conntrack
          # --no-collector.cpu
          - --no-collector.cpufreq
          - --no-collector.diskstats
          - --no-collector.edac
          - --no-collector.entropy
          - --no-collector.filefd
          - --no-collector.filesystem
          - --no-collector.hwmon
          - --no-collector.infiniband
          - --no-collector.ipvs
          - --no-collector.loadavg
          - --no-collector.mdadm
          #- --no-collector.meminfo
          - --no-collector.netclass
          - --no-collector.netdev
          - --no-collector.netstat
          - --no-collector.nfs
          - --no-collector.nfsd
          - --no-collector.pressure
          - --no-collector.rapl
          - --no-collector.schedstat
          - --no-collector.sockstat
          - --no-collector.softnet
          - --no-collector.stat
          - --no-collector.textfile
          - --no-collector.thermal_zone
          - --no-collector.time
          - --no-collector.timex
          - --no-collector.udp_queues
          - --no-collector.uname
          - --no-collector.vmstat
          - --no-collector.xfs
          - --no-collector.zfs
        ports:
        - name: metrics
          containerPort: 9100
        volumeMounts:
        - name: host
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /