---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 5s
      evaluation_interval: 1m
    scrape_configs:
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_controller_name,__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: default;node-exporter;9100
      scheme: http

