---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 5s
      evaluation_interval: 1m
    scrape_configs:
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
      - role: pod
      #
      # Exemple de suppression de Metric non utile
      #
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_cpu_guest_seconds_total'
        action: drop
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_controller_name,__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: default;node-exporter;9100
      #
      # Ajout auto du label node avec pour valeur le nom du host
      #
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      scheme: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
          - --web.enable-lifecycle
          - --web.listen-address=0.0.0.0:9090
          - --web.enable-admin-api
          - --web.page-title=Agorakube-Prometheus
          - --storage.tsdb.path=/prometheus
          - --config.file=/etc/prometheus/prometheus.yaml
          - --storage.tsdb.retention.time=30d
        ports:
        - name: metrics
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
      initContainers:
      - name: prometheus-data-set-permissions
        image: busybox
        command: ["/bin/chown","-R","65534:65534", "/prometheus"]
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
         name: prometheus-config
      - name: prometheus-data
        persistentVolumeClaim:
            claimName: prometheus-data
